[package]
name = "ape"
version = "0.3.0"
compiler = "0.12.0"
entrypoint = "lib.typ"
authors = ["Izan"]
license = "MIT"
description = "Stop monkeying around with your layouts! Get sophisticated with Ape for Typst."
categories = ["layout", "utility","report"]


[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"