[package]
name = "ape"
version = "0.3.0"
compiler = "0.13.0"
entrypoint = "lib.typ"
authors = ["Izan"]
license = "MIT"
exclude = ["exemples"]
description = "Stop monkeying around with your layouts! Get sophisticated with Ape for Typst."
categories = ["layout", "utility","report"]