[package]
name = "ape"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Izan"]
license = "MIT"
description = "An example package."

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"


